stages:
  - build
  - test
  - tag-latest


Build Image:
  stage: build
  image:
    name: registry.insight-centre.org/sit/kaniko-gitlab:latest
  script: |
    rm -r /root/.docker
    mkdir -p /kaniko/.docker
    echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    echo "Building with dest: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    /kaniko/executor --context $CI_PROJECT_DIR --skip-tls-verify --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --cache=true


test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  script:
  - cd $CI_PROJECT_DIR
  - pip install -e .
  - python --version
  - pipenv --version
  - ./run_tests.sh


Tag Latest:
  stage: tag-latest
  image:
    name: registry.insight-centre.org/sit/kaniko-gitlab:latest
  script:
    - rm -r /root/.docker
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cd $CI_PROJECT_DIR
    - echo "FROM ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}" > Dockerfile
    - /kaniko/executor --skip-tls-verify --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
